### ISSUE TITLE
AttributeError: 'str' object has no attribute 'decode' after updating to v0.8.0

### ISSUE THREAD

**Issue by Lionqueen94** [django-otp/django-otp#25]
Hi!

I just tried the new version 0.8.0 but get this error when running my tests (during test database creation):
```
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/home/ellen/.virtualenvs/sfe/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/ellen/.virtualenvs/sfe/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ellen/.virtualenvs/sfe/lib/python3.6/site-packages/django/core/management/commands/test.py", line 23, in run_from_argv
    super().run_from_argv(argv)
  File "/home/ellen/.virtualenvs/sfe/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ellen/.virtualenvs/sfe/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/home/ellen/.virtualenvs/sfe/lib/python3.6/site-packages/django/core/management/commands/test.py", line 53, in handle
    failures = test_runner.run_tests(test_labels)
  File "/home/ellen/.virtualenvs/sfe/lib/python3.6/site-packages/django/test/runner.py", line 629, in run_tests
    old_config = self.setup_databases(aliases=databases)
  File "/home/ellen/.virtualenvs/sfe/lib/python3.6/site-packages/django/test/runner.py", line 554, in setup_databases
    self.parallel, **kwargs
  File "/home/ellen/.virtualenvs/sfe/lib/python3.6/site-packages/django/test/utils.py", line 174, in setup_databases
    serialize=connection.settings_dict.get('TEST', {}).get('SERIALIZE', True),
  File "/home/ellen/.virtualenvs/sfe/lib/python3.6/site-packages/django/db/backends/base/creation.py", line 72, in create_test_db
    run_syncdb=True,
  File "/home/ellen/.virtualenvs/sfe/lib/python3.6/site-packages/django/core/management/__init__.py", line 148, in call_command
    return command.execute(*args, **defaults)
  File "/home/ellen/.virtualenvs/sfe/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/home/ellen/.virtualenvs/sfe/lib/python3.6/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/home/ellen/.virtualenvs/sfe/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 234, in handle
    fake_initial=fake_initial,
  File "/home/ellen/.virtualenvs/sfe/lib/python3.6/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/home/ellen/.virtualenvs/sfe/lib/python3.6/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/home/ellen/.virtualenvs/sfe/lib/python3.6/site-packages/django/db/migrations/executor.py", line 245, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/home/ellen/.virtualenvs/sfe/lib/python3.6/site-packages/django/db/migrations/migration.py", line 124, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/home/ellen/.virtualenvs/sfe/lib/python3.6/site-packages/django/db/migrations/operations/fields.py", line 249, in database_forwards
    schema_editor.alter_field(from_model, from_field, to_field)
  File "/home/ellen/.virtualenvs/sfe/lib/python3.6/site-packages/django/db/backends/base/schema.py", line 535, in alter_field
    old_db_params, new_db_params, strict)
  File "/home/ellen/.virtualenvs/sfe/lib/python3.6/site-packages/django/db/backends/postgresql/schema.py", line 124, in _alter_field
    new_db_params, strict,
  File "/home/ellen/.virtualenvs/sfe/lib/python3.6/site-packages/django/db/backends/base/schema.py", line 649, in _alter_field
    new_default = self.effective_default(new_field)
  File "/home/ellen/.virtualenvs/sfe/lib/python3.6/site-packages/django/db/backends/base/schema.py", line 233, in effective_default
    return field.get_db_prep_save(self._effective_default(field), self.connection)
  File "/home/ellen/.virtualenvs/sfe/lib/python3.6/site-packages/django/db/backends/base/schema.py", line 212, in _effective_default
    default = field.get_default()
  File "/home/ellen/.virtualenvs/sfe/lib/python3.6/site-packages/django/db/models/fields/__init__.py", line 801, in get_default
    return self._get_default()
  File "/home/ellen/.virtualenvs/sfe/lib/python3.6/site-packages/two_factor/models.py", line 57, in random_hex_str
    return random_hex().decode('utf-8')
AttributeError: 'str' object has no attribute 'decode'
```

It only happens when I do this update and reverting back to 0.7.5 runs my tests normally.
Do you have any idea what the issue is? I'm running Python 3.6 and Django 2.2.10 btw.

**Comment by psagers** [comment]
This appears to be a duplicate of #24 (a django-two-factor-auth issue).
